apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}-service
spec:
  selector:
    app: {{ .Values.labels.name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}

