## allows us to import and use the http.bzl from the default repo and us it with alias "http_archive".
## we can use this rule to download other rules other rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## importing the nodeJS rule using http_archive
http_archive(
    name = "aspect_rules_js", ## rule name
    sha256 = "6e4637a63acbd2ca080f463cb18fc0d7439f2401adbfe0028f3f4544c9eb8085", ## sha value (integrity check for the rule we will download)
    strip_prefix = "rules_js-2.8.1", ## request specific version
    url = "https://github.com/aspect-build/rules_js/releases/download/v2.8.1/rules_js-v2.8.1.tar.gz", ## URL for downloading the rule
)

load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies") ## loading a specific file from the rule we downloaded with http_archive

rules_js_dependencies() ## calling the loaded function

load("@aspect_rules_js//js:toolchains.bzl", "DEFAULT_NODE_VERSION", "rules_js_register_toolchains")

rules_js_register_toolchains(node_version = DEFAULT_NODE_VERSION)

load("@aspect_rules_js//npm:repositories.bzl", "npm_translate_lock")

npm_translate_lock(
    name = "npm",
    npmrc = None,
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()