Vagrant.configure("2") do |config|
  # Use CentOS 7 official box
  config.vm.box = "centos/7"

  # VM settings
  config.vm.hostname = "devop-assignment-vm"

  # Optional: Forward SSH port

  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
  end
	
  # Copy local folder into VM (one-time copy)
  config.vm.provision "file", source: "../app", destination: "/home/vagrant/app"
  config.vm.provision "file", source: "../pods.yaml", destination: "/home/vagrant/pods.yaml"


  # Provisioning (optional)
  
  # installing docker utils
  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
	echo "================================"
	echo "=== Adding Mirrors and repos ==="
	echo "================================"
	
	sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-Base.repo
	sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Base.repo
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	
	echo "==========================="
	echo "=== installing Packages ==="
	echo "==========================="
	yum install -y yum-utils docker-ce docker-ce-cli containerd.io
	curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash # install helm
	sudo yum install git -y # install git
	
	echo "======================="
	echo "=== Enable Services ==="
	echo "======================="
	systemctl start docker
	systemctl enable docker

	echo "======================"
	echo "=== Installing k3s ==="
	echo "======================"
	curl -sfL https://get.k3s.io | sh -s - --disable traefik --write-kubeconfig-mode 644 --node-name k3s-master
	ln -s /usr/local/bin/kubectl /usr/bin/kubectl # enable builtin k3s kubectl globally
	ln -s /usr/local/bin/k3s /usr/bin/k3s

	echo "======================="
	echo "=== Creating Images ==="
	echo "======================="
	
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
	cd /home/vagrant/app/backend/
    docker build -t backend-app .
    docker save -o backend-app.tar backend-app:latest
    k3s ctr images import backend-app.tar
	cd /home/vagrant/app/frontend/
    docker build -t frontend-app .
    docker save -o frontend-app.tar frontend-app:latest
    k3s ctr image import frontend-app.tar
	
	echo "======================"
	echo "=== Run Containers ==="
	echo "======================"

    cd /home/vagrant
	mkdir project
	cd prjected
	git clone --branch assignement-v2 https://github.com/YakovAvata/Devops_Assignment.git
	helm install test-app Devops_Assignment/app-charts/
	#sleep 10
	#kubectl apply -f pods.yaml
  SHELL
end