Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.box_version = "6.0.0"  

  # VM settings
  config.vm.hostname = "devop-assignment-vm"
  config.vbguest.auto_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Port Forwarding
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
  end
  

  config.vm.provision "shell", inline: <<-SHELL
    sudo -i
	echo "================================"
	echo "=== Adding Mirrors and repos ==="
	echo "================================"
	yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	
	echo "==========================="
	echo "=== installing Packages ==="
	echo "==========================="
	yum install -y yum-utils docker-ce docker-ce-cli containerd.io git
	curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash # install helm
	
	echo "======================="
	echo "=== Enable Services ==="
	echo "======================="
	systemctl start docker
	systemctl enable docker

	echo "======================"
	echo "=== Installing k3s ==="
	echo "======================"
	curl -sfL https://get.k3s.io | sh -s - --disable traefik --write-kubeconfig-mode 644 --node-name k3s-master
	ln -s /usr/local/bin/kubectl /usr/bin/kubectl # enable builtin k3s kubectl globally
	ln -s /usr/local/bin/k3s /usr/bin/k3s
	ln -s /usr/local/bin/helm /usr/bin/helm
	echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.bashrc && source ~/.bashrc

	echo "======================="
	echo "=== Creating Images ==="
	echo "======================="
	
	mkdir /home/vagrant/project
	cd /home/vagrant/project
	git clone --branch assignement-v2 https://github.com/YakovAvata/Devops_Assignment.git
	
	cd /home/vagrant/project/Devops_Assignment/app/backend/
    docker build -t backend-app .
    docker save -o backend-app.tar backend-app:latest
    k3s ctr images import backend-app.tar
	cd /home/vagrant/project/Devops_Assignment/app/frontend/
    docker build -t frontend-app .
    docker save -o frontend-app.tar frontend-app:latest
    k3s ctr image import frontend-app.tar
	
	echo "========================="
	echo "=== Deploy Helm-Chart ==="
	echo "========================="

	helm dependency update /home/vagrant/project/Devops_Assignment/app-charts/
	helm install test-app /home/vagrant/project/Devops_Assignment/app-charts/
  SHELL
end