apiVersion: v2
name: Backend app helm chart
description: Backend app helm chart
type: application
version: 0.1.0
appVersion: "1.1.0"


dependencies:
  - name: mongodb
    version: 0.1.0
    repository: "file://./charts/mongodb"
    condition: mongodb.enabled

  - name: frontend-app
    version: 0.1.0
    repository: "file://./charts/frontend-app"
    condition: frontend-app.enabled


  - name: ingress-nginx
    version: "*"    # Check latest version
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled

