metadata:
  name: backend

replicaCount: 1

image:
  repository: backend-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

labels:
  app: backend-app


ingress-nginx:
  fullnameOverride: ingress-nginx
  enabled: true
  controller:
    service:
      type: LoadBalancer
