apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.labels.app }}
