apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ .Values.metadata.name }}-ingress-service
spec:
  # ingressClassName is necessary since v1.22
  ingressClassName: nginx
  tls:
  - hosts:
    - nice-assignment.local
    secretName: my-tls-secret
  rules:
  - host: nice-assignment.local
    http:
      paths:
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.metadata.name }}-service
            port:
              number: {{ .Values.service.port }}