metadata:
  name: frontend

replicaCount: 1

image:
  repository: frontend-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80

labels:
  app: frontend-app


ingress-nginx:
  fullnameOverride: ingress-nginx
  enabled: true
  controller:
    service:
      type: LoadBalancer

